#!/usr/bin/env bash                                                                                   
# This script creates a PID file, displays messages, and handles signals
killer() {                                                                                            
    rm /var/run/myscript.pid                                                                          
    exit 0                                                                                            
}                                                                                                     
                                                                                                      
trap "echo 'I hate the kill command' && killer" SIGTERM                                               
trap "echo 'Y U no love me?!'" SIGINT                                                                 
trap "killer" SIGQUIT                                                                                 
echo '$$' > /var/run/myscript.pid                                                                     
while true                                                                                            
do                                                                                                    
  echo "To infinity and beyond"                                                                       
  sleep 2                                                                                             
done      
