#!/usr/bin/env bash
# Bash (init) script that manages `manage_my_process`

killer() {
    if [ -f /var/run/my_process.pid ]; then
        pid=$(cat /var/run/my_process.pid)
        kill "$pid"
        rm /var/run/my_process.pid
    fi
}

if [[ "$1" == "start" ]]; then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [[ "$1" == "stop" ]]; then
    killer
    echo "manage_my_process stopped"
elif [[ "$1" == "restart" ]]; then
    killer
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
