#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n $pid ]]; then
    # Send SIGTERM signal to the process
    kill "$pid" >/dev/null 2>&1
else
    echo "Process is not running"
fi
    
