#!/usr/bin/env bash
# This script kills the 7-highlander process
:'
# Find the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

if [[ -n $pid ]]; then
    # Send SIGTERM signal to the process
    kill "$pid"
    echo "7-highlander process stopped successfully."
else
    echo "7-highlander process is not running."
fi
used -SIGKILL whose signal code is {9}
'

pkill -f -9 7-highlander
